// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgIUI4npXhB4MjLzFRd8fikp6J8qr3ls0',
    appId: '1:81504454499:web:f2510619d298bcf6f97556',
    messagingSenderId: '81504454499',
    projectId: 'race-timer-tracker',
    authDomain: 'race-timer-tracker.firebaseapp.com',
    storageBucket: 'race-timer-tracker.firebasestorage.app',
    measurementId: 'G-3ZXSLHH74P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAobDDgUtGAbbAjWQhCVPaMAhqZ5_J0NyU',
    appId: '1:81504454499:android:23f8370c2db0f93ef97556',
    messagingSenderId: '81504454499',
    projectId: 'race-timer-tracker',
    storageBucket: 'race-timer-tracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-59mgcSiaZxUnQ1bRI3dnSJTeZHTdx9I',
    appId: '1:81504454499:ios:f532ac7943053bb5f97556',
    messagingSenderId: '81504454499',
    projectId: 'race-timer-tracker',
    storageBucket: 'race-timer-tracker.firebasestorage.app',
    iosBundleId: 'com.example.raceTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-59mgcSiaZxUnQ1bRI3dnSJTeZHTdx9I',
    appId: '1:81504454499:ios:f532ac7943053bb5f97556',
    messagingSenderId: '81504454499',
    projectId: 'race-timer-tracker',
    storageBucket: 'race-timer-tracker.firebasestorage.app',
    iosBundleId: 'com.example.raceTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgIUI4npXhB4MjLzFRd8fikp6J8qr3ls0',
    appId: '1:81504454499:web:e769eaa8fdb7c7b4f97556',
    messagingSenderId: '81504454499',
    projectId: 'race-timer-tracker',
    authDomain: 'race-timer-tracker.firebaseapp.com',
    storageBucket: 'race-timer-tracker.firebasestorage.app',
    measurementId: 'G-RP060FB50Y',
  );
}
